In [2]:
import pandas as pd
import numpy as np
import pyproj
import folium

In [45]:
def project_array(coord, p1_type, p2_type):
    """
    좌표계 변환 함수
    - coord: x, y 좌표 정보가 담긴 NumPy Array
    - p1_type: 입력 좌표계 정보 ex) epsg:5179
    - p2_type: 출력 좌표계 정보 ex) epsg:4326
    """
    p1 = pyproj.Proj(init=p1_type)
    p2 = pyproj.Proj(init=p2_type)
    fx, fy = pyproj.transform(p1, p2, coord[:, 0], coord[:, 1])
    return np.dstack([fx, fy])[0]

In [105]:
df_tmp = pd.read_csv("./data/elevation/서울특별시 중랑구.txt", sep = ' ', header = None)

In [106]:
df_tmp['좌표정보(x)'] = df_tmp[0]
df_tmp['좌표정보(y)'] = df_tmp[1]
df_tmp.rename(columns={2:'고도'},inplace=True)
df_tmp['좌표정보(x)'] = pd.to_numeric(df_tmp['좌표정보(x)'], errors="coerce")
df_tmp['좌표정보(y)'] = pd.to_numeric(df_tmp['좌표정보(y)'], errors="coerce")

df_tmp = df_tmp.dropna()
df_tmp.index=range(len(df_tmp))
coord = np.array(df_tmp)
p1_type = "epsg:5186"
p2_type = "epsg:4326"

# project_array() 함수 실행
result = project_array(coord, p1_type, p2_type)
df_tmp['경도'] = result[:, 0]
df_tmp['위도'] = result[:, 1]
df_tmp = df_tmp.drop(columns=[0,1])
df = pd.concat([df,df_tmp])
df

C:\anaconda\lib\site-packages\pyproj\crs\crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\anaconda\lib\site-packages\pyproj\crs\crs.py:130: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
C:\Users\조영재\AppData\Local\Temp\ipykernel_14020\2093212355.py:10: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  fx, fy = pyproj.transform(p1, p2, coord[:, 0], coord[:, 1])

          고도    좌표정보(x)    좌표정보(y)          경도         위도
0      16.78  200305.31  547459.91  127.003454  37.526632
1       9.62  200305.31  547369.91  127.003454  37.525821
2       5.69  200305.31  547279.91  127.003454  37.525010
3       5.38  200305.31  547189.91  127.003454  37.524199
4      19.62  200395.31  547549.91  127.004472  37.527443
...      ...        ...        ...         ...        ...
3149  132.81  210697.72  554846.65  127.121131  37.593124
3150  121.28  210697.72  554756.65  127.121129  37.592313
3151  113.31  210697.72  554666.65  127.121128  37.591502
3152  146.72  210787.72  555026.65  127.122152  37.594745
3153  126.35  210787.72  554936.65  127.122151  37.593934

[111537 rows x 5 columns]

In [107]:
df.to_csv('./data/elevation/seoul_elevation.csv',index=False)